### ISSUE TITLE
Noise problem

### ISSUE THREAD

**Issue by bacTlink** [helenl9098/ddgi_minecraft#11]
When I run your program, I noticed some artifacts on the screen. They looked like some noise.
Then I zoomed in on the picture on the project home page and found that you had the same problem.
Is it a bug? or a problem of DDGI?

**Comment by helenl9098** [comment]
Since the direct lighting only renders also have these artifacts, we can presume that these speckles are not an inherent issue in DDGI and could be the result of a few calculations: 
1) shadow acne caused by incorrect offsetting (often too little) of the ray intersection point 
2) floating point error when intersecting the ray against the implicit surfaces (either surface or light source or probe)

We would have to play with the intersection offset value, the sample rate / number of bounces, and the implicit surface intersection calculation to know for sure. Additionally, there is no de-noising or antialiasing applied to our path tracer. This project was more of a proof of concept done over the course of 4 weeks, so there's always places to improve ~~ For more bugs specifically related to DDGI, I would reference the paper and their official code since I'm sure they'd be able to provide more insight :)
